### PR TITLE
fval.xsl: fix xsl for Firefox, fix JS for checkboxes

### PR DESCRIPTION
**Pull request by moyogo**

### CODE REVIEW

**Comment by HinTak** [comment]
That's not where the change should be made. I duplicated the fIle in bin because the binary needs it there when run. There is another copy in the source directory, and when something like 'make install' happens, to install to some place outside, the bin copy will be removed. Likewise the chm help file, for example, when it is buildable in an easie way. So the bin copy is considered the derived copy, and not to stay.

**Comment by HinTak** [comment]
That's leave aside whether the change should be make. May I ask what issue does it fix?

**Comment by HinTak** [comment]
Also, for change in that area ("improve usage under firefox"), you will need to test that it does not break usage with current MS IE, as well as the rather old MS IE based built-in XML viewer.

For the latter, you'll need to try it with the win32 hybrid binary.

http://sourceforge.net/projects/hp-pxl-jetready/files/private-test-data/stuff_special_usage_only/hybrid-win32-2015_11_12-bins.zip/download

See 'win32 hybrid branch' on page 17 of dev slide for what it is.

**Comment by HinTak** [comment]
Regarding
https://github.com/HinTak/Font-Validator/blob/5273891bf20f3918402f94c7bb77259c863d43c2/README-extra.txt#L50, I don't think so.

My firefox simply does not display *anything* (i.e. blank screen) when attempting to load XML. This is bizarre as it should treat it as text at least. And I am talking about on-the-fly loading the XML with the xsl style without generating an intermediate html. MS IE is capable of doing that, obviously. As for firefox's native XML display capability, it may need an add-on. I have not looked into this issue much - I rarely look at individual reports, and more often just grep for stuff I need to read :-).

Mono provides an implementation of System.WebBrowser (sp?) namespace, based on gecko, which supposedly is compatible with MS dotnet's provision for applications which needs an embedded web browser. It seems incomplete and/or in any case, I have not been able to get it to work.
If you feel like workng in this area, look at FontVal/ResultsForm.cs, for all the "#if !__MonoCS__".

**Comment by moyogo** [comment]
@HinTak which version of Firefox are you using? I tested on Linux, Windows and OS X and Firefox was showing the report.xml as in the screenshot above and as the other browsers after this fix. Safari and Chrome (with --allow-file-access-from-files) only has the issue with the JS for the checkboxes not working.

**Comment by HinTak** [comment]
Currently 42.0 . apparently I was using 41.0.2 end of October, and upgrade to 39.0 mid-July. Some googlng said it might be conflicting extensions - I have two, mega and noscript. I have not bothered enough to uninstall either to see which one breaks (if it is indeed the cause). But maybe you can try installing either or both to see if it breaks yours :-).

**Comment by HinTak** [comment]
Strangely enough, my current firefox setting can view XML direct now. I just haven't tried since July-ish. Yes, If I  right-click and choose 'untrust file:///", I can get the old broken behavior; so maybe I changed it myself some time in the last few months. I'll possbly leave that line in for a while, just in case it comes back.

The xsltproc line in the readme was added because I couldn't view directly; while that's no longer the case (finger-crossed...), if chrome blocks xsl by default, it might be a good idea to mention that in the readme, or work around it.

dotnet has a built-in API for doing xslt transform - with XslCompiledTransform.Transform(). I though of adding that in as an option to the CMD tool ("-html" to generate html also), but haven't got round to do it yet.

**Comment by aaronbell** [comment]
@HinTak Does this fix work for you? I want to make sure we don't get out of sync just yet.

**Comment by HinTak** [comment]
@aaronbell My previous comment was based on the fact that the existing xsl should work correctly for MSIE (the older versions) - after all, that's what the GUI has always used for years. So I provided the new hybrid binary for testing. Changes in this area must not break existing functionality/compatibility with MSIE, sacrificing one broswer for another. I don't think I know javascript well enough to review the actual change itself (nor can find time to). I hope somebody else can review the code change itself.

**Comment by HinTak** [comment]
The issue title is misleading - it is not a javascript issue, but an XSLT issue - and I do know XSLT well enough (just very rusty - I read the XSLT spec cover to cover about 15 years ago in the line of duty and did some work in that area) - and a quick google'ing give me the answer:

It is the 3rd question in the mozilla XSLT FAQ:
https://developer.mozilla.org/en/docs/XSL_Transformations_in_Mozilla_FAQ

and there is a 14 year old bug with a long discussion on it:

https://bugzilla.mozilla.org/show_bug.cgi?id=98168
'Bug 98168 - (doe) <xsl:text disable-output-escaping="yes"> not working'

I am not sure the submitted pull is the right fix, although it did remove all usage of the disable-output-escaping attribute. So I am not going to merge this pull until I think it through.

**Comment by moyogo** [comment]
> The issue title is misleading - it is not a javascript issue, but an XSLT issue

@HinTak Two issues are addressed a XSL one and a JS one.

**Comment by HinTak** [comment]
The only javascript change I can see is equivalent to replacing:

rowColl = document.all.tags("TR");

with

 if (typeof document.all.tags != "undefined")
{
rowColl = document.all.tags("TR");
}
else
{
rowColl = document.getElementsByClassName(row_classname);
}

And I think there is probably an FAQ somewhere, possibly about DOM difference? Probably not really a javascript issue but a DOM issue.

**Comment by HinTak** [comment]
The DOM issue is't too difficult to find - it is another FAQ on mozilla's.

https://developer.mozilla.org/en-US/docs/Using_Web_Standards_in_your_Web_Pages/Using_the_W3C_DOM

I'd prefer that 'if (typeof document.all.tags != "undefined")' be something like "if browserid = MSIE",
since that's what it is - it is a non-W3C behavior of MSIE. Although, Font Validator started off with MSIE-based XML viewer integrated.

**Comment by HinTak** [comment]
I have just made a change:
HinTak@8a7c171
to auto-generate html on non-windows. This would work around the XSLT issue - seening as firefox's noscript extension won't load local files, nor chrome by default, so it probably should be done. do you want that for windows also? (i.e. you are on windows do not want to use MSIE).

Still need something for the DOM issue; but that's something one needs to revisit when we have a new XML viewing functionality, and/or updating the MSIE-base viewer code (if we can persuade Microsoft to do that). See also https://github.com/HinTak/Font-Validator/issues/6

**Comment by HinTak** [comment]
Modification to the xsl file also have some implication to how the Mac OS X native stand-alone executable is built:
https://github.com/HinTak/Font-Validator/issues/7
basically, when the dll/exe's is embeded inside a static mini- mono runtime, they don't know where they are (since they are in memory only), and the current mechanism of of finding it - i.e. by the exe asking "where am I? I want to find a neighbouring file next to I am" - no longer works.

**Comment by moyogo** [comment]
@HinTak Generating HTML directly sounds good to spare the xsltproc step for people who use Chrome.

**Comment by HinTak** [comment]
@moyogo auto-generating HTML is now the default on non-windows. Do you want that for windows also?

I have managed to get the Font Validator GUI to use webkit (the rendering library behind safari/chrome) to display the XML reports on linux. On Wine, it would use gecko (the rendering library behind firefox; gecko is the standard on wine to emulate IE).

With the pre-change fval.xsl, webkit shows an an error:

@29: TypeError: NodeList is not a function (evaluating 'rowColl(i)')

and the error is gone after the change; firefox also benefit from the change, but gecko does not like it before nor after.

One other thing I have with your change is the amount of white-space changes (and re-indenting) it adds. are you running git on cygwin?

Amazingly I have got the XML display to work with webkit and gecko, without breaking too much the original IE-based functionalities. Broke only the search-text functionality with IE - or rather, the hybrid build and default build of the next release I make will have functional XML display on both windows and Linux, and they differ only in that one can search for text on the the hybrid build on windows.

**Comment by sjvudp** [comment]
I just discovered this closed pull request after having added my own pull request that seems to deal with the same problem (about four years later). Meaning: It's still broken on Linux/Firefox.

**Comment by davelab6** [comment]
But isn't this fixed in hintaks version?

**Comment by HinTak** [comment]
@sjvudp : on Linux, with my fork, there should be an additional accompanying html report. The works fine with Firefox 64.

**Pull request merged**
